---
title: "hw6_anna_hyunjung_kim"
format: html
editor: visual
---

# Load the liabraries

```{r}
#install.packages(c("tidyverse", "tidytext", "janeaustenr", "wordcloud", "stringr"))
#install.packages("textdata")

library(tidyverse)
library(tidytext)   
library(janeaustenr) 
library(stringr)
library(wordcloud)  
```

# Load Data Set

```{r}
austen <- austen_books()
austen

```

# Data Organizing

```{r}
#Group by book
emma_data <- austen %>%
  group_by(book) %>%
  filter(book == "Emma")

#emma_data 
# Create linenumber and chapter columns.
# detect chapter boundaries using regex
chapter_data <- emma_data %>% 
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter\\s+\\d+\\b"))))


#chapter_data
```

# Tokenization

```{r}
data(stop_words) 

# Use unnest_tokens() to tokenize text into individual words.
emma_words <- chapter_data %>%
  unnest_tokens(word, text) %>% 
  mutate(word = str_extract(word, "[a-z']+")) %>%  
  filter(!is.na(word)) %>% 
  anti_join(stop_words, by = "word") 

emma_words
```

# A. NRC sentiment analysis + plots

```{r}
# apply sentiment filters for joy
nrc_joy <- get_sentiments("nrc") %>%
  filter(sentiment == "joy") %>%
  distinct(word)

nrc_joy

emma_nrc_counts <- emma_words %>%
  semi_join(nrc_joy, by = "word") %>%
  count(word, sort = TRUE) %>%
  filter(n > 50)

emma_nrc_counts 
```

## a.1. Bar plot

```{r}
# Bar chart
ggplot(emma_nrc_counts, aes(x = reorder(word, n), y = n)) +
  geom_col(fill = "blue") +
  coord_flip() +
  labs(title = "Frequent Joy Words in Emma (NRC)",
       x = "Word", y = "Frequency")
```

## a.2. Word Cloud

```{r}
set.seed(123)
wordcloud(words = emma_nrc_counts$word,
          freq = emma_nrc_counts$n,
          max.words = 100,
          colors = brewer.pal(8, "Dark2"))
```

# B. AFINN sentiment analysis + plots

```{r}
# apply sentiment filters for afinn
afinn_pos <- get_sentiments("afinn") %>%
  filter(value >= 1) %>%
  distinct(word)

afinn_pos 
```

```{r}

emma_afinn_counts <- emma_words %>%
  semi_join(afinn_pos, by = "word") %>%
  count(word, sort = TRUE) %>%
  filter(n > 50)

emma_afinn_counts
```

## b.1. bar plot

```{r}
ggplot(emma_afinn_counts, aes(x = reorder(word, n), y = n)) +
  # green color is too bright so darkgreen 
  geom_col(fill = "darkgreen") +
  coord_flip() +
  labs(title = "Frequent Positive Words in Emma (AFINN)",
       x = "Word", y = "Frequency")
```

## b.2. Word Cloud

```{r}
set.seed(123)
wordcloud(words = emma_afinn_counts$word,
          freq = emma_afinn_counts$n,
          max.words = 100,
          colors = brewer.pal(8, "Set1"))
```

# BING sentiment analysis + plots

```{r}
# apply sentiment filters for bing
bing_pos <- get_sentiments("bing") %>%
  filter(sentiment == "positive") %>%
  distinct(word)

bing_pos 

emma_bing_counts <- emma_words %>%
  semi_join(bing_pos, by = "word") %>%
  count(word, sort = TRUE) %>%
  filter(n > 50)

emma_bing_counts 
```

## c.1. Bar Plot

```{r}
ggplot(emma_bing_counts, aes(x = reorder(word, n), y = n)) +
  geom_col(fill = "pink") +
  coord_flip() +
  labs(title = "Frequent Positive Words in Emma (BING)",
       x = "Word", y = "Frequency")
```

## C.2. Word Cloud

```{r}
set.seed(123)
wordcloud(words = emma_bing_counts$word,
          freq = emma_bing_counts$n,
          max.words = 100,
          colors = brewer.pal(8, "Paired"))
```
